### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by rtaupe** [siemens/JMiniZinc#27]
Hi!
I'm having a compilation error, can you please help me to compile and build the jars?
My first problem was: [FATAL] Non-resolvable parent POM when compiling the diagnosis and the ui projects.  I changed the <version>1.4</version> in the pom files that had 1.4.3 and run everything again. After this, I was able to compile the core and diagnosis projects.
My current problem is with the ui project, I have several compilation errors and don't know how to fix them. 
I attach a file with the output obtained after executing: mvn  clean install.
Kind regards, 

Angela
[output.txt](https://github.com/siemens/JMiniZinc/files/2738474/output.txt)

_Originally posted by @angievig in https://github.com/siemens/JMiniZinc/commit/4251d690c7dc2cbf6ac449e74b3a3f43fbdd9ef6#commitcomment-31875053_

**Comment by rtaupe** [comment]
Hi Angela,

thank you for reporting this!
The compilation errors in the ui project have been introduced by d7b58ff6db00db79301ea26c61f1b31be3408d25, I am currently working on fixing them.

Richard
